import socket

s = socket.socket()
host = socket.gethostname()
port = 8080
s.bind((host, port))
s.listen(1)

print("Proses Empat Koneksi")

conn1, addr1 = s.accept()
print("Client_1 terkoneksi")
conn1.send("Selamat datang di Server...".encode())
conn2, addr2 = s.accept()
print("Client_2 terkoneksi")
conn2.send("Selamat datang di Server...".encode())
conn3, addr3 = s.accept()
print("Client_3 terkoneksi")
conn3.send("Selamat datang di Server...".encode())
conn4, addr4 = s.accept()
print("Client_4 terkoneksi")
conn4.send("Selamat datang di Server...".encode())

while 1:
    message = input("Masukan Pesan : ")
    message = str(message).encode()
    conn1.send(message)
    conn2.send(message)
    conn3.send(message)
    conn4.send(message)
    print("Pesan Terkirim")
    recv_message = conn1.recv(1024)
    print("Client_1 : ", recv_message.decode())
    conn2.send(recv_message)
    conn3.send(recv_message)
    conn4.send(recv_message)
    recv_message = conn2.recv(1024)
    print("Client_2 : ", recv_message.decode())
    conn1.send(recv_message)
    conn3.send(recv_message)
    conn4.send(recv_message)
    recv_message = conn3.recv(1024)
    print("Client_3 : ", recv_message.decode())
    conn1.send(recv_message)
    conn2.send(recv_message)
    conn4.send(recv_message)
    recv_message = conn4.recv(1024)
    print("Client_4 : ", recv_message.decode())
    conn1.send(recv_message)
    conn2.send(recv_message)
    conn3.send(recv_message)
